version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - network_test
    www:
        image: jsalcedo90/ejemplodockerlaravel:1.1
        ports: 
            - 80:80
        environment:
            DB_HOST: host.docker.internal
        volumes:
            - .:/var/www/html
        links:
            - db
        networks:
            - network_test
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - network_test
volumes:
    persistent:
networks: 
    network_test:
